name: Build REG-linux QT6

on:
  push: 
    branches: [ "*" ]

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build REG-linux QT6
    runs-on: ubuntu-latest
    container: reglinux/reglinux-build:latest
    outputs:
      qtversion: ${{ steps.compile_step.outputs.qtversion }}
      sufixdate: ${{ steps.compile_step.outputs.sufixdate }}
      dorelease: ${{ false || steps.compile_step.outputs.dorelease }}
    strategy:
      matrix:
        platform: [bcm2711]
    steps:
      - name: Compile ${{ matrix.platform }}
        id: compile_step
        shell: bash
        run: |
          git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./REG-LINUX
          cd REG-LINUX
          git submodule init
          git submodule update

          rm -rf .git .github
          # After each package is compiled and installed, delete build folder
          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\tfind $(BUILD_DIR) -mindepth 1 -maxdepth 1 -type d -not iname "buildroot-config" -printf "%T\@\\t%p\\n" | sort -g | head -n -5 | cut -f 2- | xargs -d $"\\n" sh -c "for arg do cd "\$arg"; shopt -s extglob; rm -rvf \!\(\.stamp*|\.br*|\.config\); shopt -u extglob; done" _ \
          	du -h -s $(PWD) \
          	df -Ph $(PWD) \n :' buildroot/package/pkg-generic.mk
          # After each downloaded package is extracted, delete older and keep latest 3
          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -3 | cut -f 2- | xargs rm -rfv :' buildroot/package/pkg-generic.mk
         
          # Enable the flag to build QT6 from source
          sed -i s/#BR2_PACKAGE_REGLINUX_QT6=y/BR2_PACKAGE_REGLINUX_QT6=y/ configs/reglinux-board.common
          sed -i s/#BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/ configs/reglinux-board.common
          sed -i s/#BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/ configs/reglinux-board.common

          # Version
          qtversion=$(grep -m 1 REGLINUX_QT6_VERSION package/libraries/reglinux-qt6/reglinux-qt6.mk | sed -e "s/.*=[ ]*//")
          echo "qtversion=${qtversion}" >> "$GITHUB_OUTPUT"

          pwd

          # Build
          CUSTOM_DIR=${GITHUB_WORKSPACE}/REG-LINUX/custom BUILDROOT_DIR=${GITHUB_WORKSPACE}/REG-LINUX/buildroot ${GITHUB_WORKSPACE}/REG-LINUX/scripts/linux/mergeToBR.sh
          mkdir -p ${GITHUB_WORKSPACE}/REG-LINUX/output/${{ matrix.platform }}
          ${GITHUB_WORKSPACE}/REG-LINUX/configs/createDefconfig.sh ${GITHUB_WORKSPACE}/REG-LINUX/configs/reglinux-${{ matrix.platform }}
          CCACHE_DISABLE=1 make O_=${GITHUB_WORKSPACE}/REG-LINUX/output/${{ matrix.platform }} BR2_EXTERNAL=${GITHUB_WORKSPACE}/REG-LINUX -C ${GITHUB_WORKSPACE}/REG-LINUX/buildroot reglinux-${{ matrix.platform }}_defconfig
          CCACHE_DISABLE=1 make O_=${GITHUB_WORKSPACE}/REG-LINUX/output/${{ matrix.platform }} BR2_EXTERNAL=${GITHUB_WORKSPACE}/REG-LINUX -C ${GITHUB_WORKSPACE}/REG-LINUX/buildroot reglinux-qt6
          
          # Create built output directory
          mkdir -p ${GITHUB_WORKSPACE}/REG-QT6-COMPILED

          # Create package
          cd ${GITHUB_WORKSPACE}/REG-LINUX/output/${{ matrix.platform }} || exit 1
          staging="$(cat build/staging.dir)"
          cat build/host-qt6*/.files-list-host.txt | cut -d ',' -f 2 | sed -e 's/\.\//host\//g' >qt6-host-files.txt
          cat build/qt6*/.files-list-staging.txt | cut -d ',' -f 2 | sed -e "s+\.\/+$staging\/+g" >qt6-staging-files.txt
          cat build/qt6*/.files-list.txt | cut -d ',' -f 2 | sed -e 's/\.\//target\//g' >qt6-target-files.txt
          cat qt6-host-files.txt qt6-staging-files.txt qt6-target-files.txt >filelist.txt
          find . | grep /host/ | grep Qt >>filelist.txt
          find . | grep /target/ | grep Qt >>filelist.txt
          awk -i inplace '!seen[$0]++' filelist.txt
          tar cvzf  ${GITHUB_WORKSPACE}/REG-QT6-COMPILED/reglinux-qt6-${qtversion}"-${{ matrix.platform }}.tar.gz -T filelist.txt
          
          # Do release
          echo "dorelease=${{ true }}" >> "$GITHUB_OUTPUT"

      - name: upload_artifacts_${{ matrix.platform }}
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reglinux-qt6-${{ steps.compile_step.outputs.qtversion }}-${{ matrix.platform }}
          path: ./REG-QT6-COMPILED/
        
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.dorelease && ! cancelled() }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./REG-QT6-COMPILED/
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: ./REG-QT6-COMPILED/**/reglinux-qt6-*
          tag_name: ${{ needs.build.outputs.qtversion }}
          prerelease: false
          generate_release_notes: true
          name: ${{ needs.build.outputs.qtversion }}
